### ISSUE TITLE
font issue

### ISSUE THREAD

**Issue by ghost1372** [AndrewKeepCoding/AK.Toolkit#1] opened 2022-04-22 07:50 UTC
using **MS Gothic** font is not good option, this is my output
![Untitled](https://user-images.githubusercontent.com/9213496/164641233-e5afdc5f-7363-4c51-9968-b5719c201017.png)

You should resolve this issue without changing the font.

**Comment by AndrewKeepCoding** [comment] 2022-04-22 11:02
Hi @ghost1372! Thanks for checking it out! I totally agree with you. I was going to find a way to get the whole width of the input text and use it to offset the Placeholder. I found a few ways to get the width but those were a bit tricky and I wanted this to be as simple as possible. I'll take another look but if you have something in mind, I'd appreciate the help😁

**Comment by AndrewKeepCoding** [comment] 2022-04-22 22:18
I guess I need to wait for this issue (microsoft/microsoft-ui-xaml#808). There seems to be a difference in the rendering between TextBoxes and TexBlocks.

**Comment by ghost1372** [comment] 2022-04-23 11:18
tnx
Can we use TextBox instead of the TextBlock? mybe with a little change in style we can make it look like a TextBlock

**Comment by AndrewKeepCoding** [comment] 2022-04-25 10:41
I followed your suggestion and created a [branch](https://github.com/AndrewKeepCoding/AK.Toolkit/tree/feature-better-suggestion-method-with-textbox-control). But instead of changing the style, which will be ending pulling the whole TextBox style, I added a TextBox control programmatically. I'll be checking a few things but I think I'll be updating the NuGet package in a day. Thanks again 😀

**Comment by ghost1372** [comment] 2022-04-25 14:30
tnx but it seems that seggestion not working
![Animation](https://user-images.githubusercontent.com/9213496/165110277-0a81843a-eba3-4387-8bcb-5897dadb44a4.gif)

**Comment by ghost1372** [comment] 2022-04-26 15:34
Hi @AndrewKeepCoding sorry for late response.  I used your codes and this is result:

![Animation](https://user-images.githubusercontent.com/9213496/165337587-4c4cc919-60d9-40ab-af2f-1e3aa204db86.gif)

1. I cant see suggestion!
2. Foreground property is not working
3. pressing Right Key from keyboard is working and select suggestion but i cant see suggestion itself

**Comment by AndrewKeepCoding** [comment] 2022-04-26 21:08
Finally I got to reproduce the problem by changing my Windows to the **Light** mode.

These are the facts so far (Windows 10/11):

- [ ] ``Foreground`` is not working on both Light mode and Dark mode.
- [ ] It's not showing the suggestion on Light mode.
- [ ] Not sure if ``SuggestionForeground`` is working on Light mode.

**Comment by AndrewKeepCoding** [comment] 2022-04-27 13:28
Created new issue #3. Closing this. @ghost1372 see you there.

**Closed by AndrewKeepCoding** 2022-04-27 13:28 UTC
